spring:

  # security:
  #   user:
  #     name: daniel
  #     password: daniel
  #     roles: manager
  datasource:
    url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfnotExist=true
    username: root
    password: Manassedaniel2001@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8181

flickr: 
  apiKey: 7685fb2aaef020bd06826895722a6b21
  apiSecret: d4cf4ee01306e6d8
  appKey: 72157720890663320-3e8863b5da7ea3e6
  appSecret: 04cf58b901f3d224

  
